// Download latin-subset variable woff2 files from Google Fonts and emit a
// self-hosted @font-face stylesheet. Only the `latin` subset is kept so we
// ship 1 file per family instead of the full unicode-range matrix.
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const CSS = join('/tmp/opencode', 'gf.css');
const OUT_DIR = process.argv[2];
const OUT_CSS = process.argv[3];
const slug = (f) => f.toLowerCase().replace(/\s+/g, '-');

const css = await import('node:fs').then((fs) => fs.readFileSync(CSS, 'utf8'));

// Split into `/* subset */ @font-face {...}` chunks.
const blocks = css.split('/*').slice(1);
const picked = [];
for (const block of blocks) {
  const subset = block.slice(0, block.indexOf('*/')).trim();
  if (subset !== 'latin') continue;
  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
  const weight = /font-weight:\s*([\d ]+)/.exec(block)?.[1];
  const url = /url\((https:[^)]+)\)/.exec(block)?.[1];
  if (!family || !url) continue;
  picked.push({ family, weight: weight.trim(), url });
}

mkdirSync(OUT_DIR, { recursive: true });

const faces = [];
let total = 0;
for (const { family, weight, url } of picked) {
  const file = `${slug(family)}-latin-var.woff2`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${family}: HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  total += buf.byteLength;
  writeFileSync(join(OUT_DIR, file), buf);
  faces.push(
    `/* ${family} ${weight} — latin subset, variable weight axis */\n@font-face {\n` +
      `  font-family: '${family}';\n` +
      `  font-style: normal;\n` +
      `  font-weight: ${weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('/fonts/${file}') format('woff2');\n` +
      `  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA,\n` +
      `    U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,\n` +
      `    U+2212, U+2215, U+FEFF, U+FFFD;\n}`
  );
  console.log(`${file.padEnd(34)} ${(buf.byteLength / 1024).toFixed(1)} KB  (${family} ${weight})`);
}

writeFileSync(
  OUT_CSS,
  `/* AUTO-GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.\n` +
    ` * Self-hosted latin-subset variable fonts: no third-party CSS request,\n` +
    ` * no render-blocking <link>, no FOUT layout shift from a late stylesheet.\n */\n\n` +
    faces.join('\n\n') +
    '\n'
);
console.log(`\ntotal woff2: ${(total / 1024).toFixed(1)} KB across ${picked.length} files`);